name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v2

    - name: Init new repo in dist folder and commit generated files
      run: |
        python renderer.py
        mkdir docs
        cd docs/
        cp ../tmp_skynetallow skynetallow

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment

      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
